#!/bin/bash

python main_RandomSearch.py SEER_noPreprocessOneEvent_1 |& tee log-SEER_noPreprocessOneEvent_1.txt
python main_RandomSearch.py SEER_noPreprocessOneEvent_12 |& tee log-SEER_noPreprocessOneEvent_12.txt
python main_RandomSearch.py SEER_noPreprocessOneEvent_123 |& tee log-SEER_noPreprocessOneEvent_123.txt
python main_RandomSearch.py SEER_noPreprocessOneEvent_1234 |& tee log-SEER_noPreprocessOneEvent_1234.txt
python main_RandomSearch.py SEER_noPreprocessOneEvent_4123 |& tee log-SEER_noPreprocessOneEvent_4123.txt
python main_RandomSearch.py SEER_noPreprocessOneEvent_5123 |& tee log-SEER_noPreprocessOneEvent_5123.txt
python main_RandomSearch.py SEER_noPreprocessOneEvent_6123 |& tee log-SEER_noPreprocessOneEvent_6123.txt
python main_RandomSearch.py SEER_noPreprocessOneEvent_7123 |& tee log-SEER_noPreprocessOneEvent_7123.txt
python main_RandomSearch.py SEER_noPreprocessOneEvent_8123 |& tee log-SEER_noPreprocessOneEvent_8123.txt
python main_RandomSearch.py SEER_noPreprocessOneEvent_9123 |& tee log-SEER_noPreprocessOneEvent_9123.txt