#!/bin/bash

python summarize_results.py SEER_noprocessing_1 |& tee log-test-SEER_noprocessing_1.txt
python summarize_results.py SEER_noprocessing_12 |& tee log-test-SEER_noprocessing_12.txt
python summarize_results.py SEER_noprocessing_123 |& tee log-test-SEER_noprocessing_123.txt
python summarize_results.py SEER_noprocessing_1234 |& tee log-test-SEER_noprocessing_1234.txt
python summarize_results.py SEER_noprocessing_4123 |& tee log-test-SEER_noprocessing_4123.txt
python summarize_results.py SEER_noprocessing_5123 |& tee log-test-SEER_noprocessing_5123.txt
python summarize_results.py SEER_noprocessing_6123 |& tee log-test-SEER_noprocessing_6123.txt
python summarize_results.py SEER_noprocessing_7123 |& tee log-test-SEER_noprocessing_7123.txt
python summarize_results.py SEER_noprocessing_8123 |& tee log-test-SEER_noprocessing_8123.txt
python summarize_results.py SEER_noprocessing_9123 |& tee log-test-SEER_noprocessing_9123.txt