#!/bin/bash

python main_RandomSearch.py SEER_1 |& tee log-SEER_1.txt
python main_RandomSearch.py SEER_12 |& tee log-SEER_12.txt
python main_RandomSearch.py SEER_123 |& tee log-SEER_123.txt
python main_RandomSearch.py SEER_1234 |& tee log-SEER_1234.txt
python main_RandomSearch.py SEER_4123 |& tee log-SEER_4123.txt
python main_RandomSearch.py SEER_5123 |& tee log-SEER_5123.txt
python main_RandomSearch.py SEER_6123 |& tee log-SEER_6123.txt
python main_RandomSearch.py SEER_7123 |& tee log-SEER_7123.txt
python main_RandomSearch.py SEER_8123 |& tee log-SEER_8123.txt
python main_RandomSearch.py SEER_9123 |& tee log-SEER_9123.txt

