#!/bin/bash

python summarize_results.py crash2da_1 |& tee log-test-crash2da_1.txt
python summarize_results.py crash2da_12 |& tee log-test-crash2da_12.txt
python summarize_results.py crash2da_123 |& tee log-test-crash2da_123.txt
python summarize_results.py crash2da_1234 |& tee log-test-crash2da_1234.txt

python summarize_results.py crash2da_4123 |& tee log-test-crash2da_4123.txt
python summarize_results.py crash2da_5123 |& tee log-test-crash2da_5123.txt
python summarize_results.py crash2da_6123 |& tee log-test-crash2da_6123.txt
python summarize_results.py crash2da_7123 |& tee log-test-crash2da_7123.txt
python summarize_results.py crash2da_8123 |& tee log-test-crash2da_8123.txt
python summarize_results.py crash2da_9123 |& tee log-test-crash2da_9123.txt
