#!/bin/bash

python summarize_results.py SEER_1 |& tee log-test-SEER_1.txt
python summarize_results.py SEER_12 |& tee log-test-SEER_12.txt
python summarize_results.py SEER_123 |& tee log-test-SEER_123.txt
python summarize_results.py SEER_1234 |& tee log-test-SEER_1234.txt
python summarize_results.py SEER_4123 |& tee log-test-SEER_4123.txt
python summarize_results.py SEER_5123 |& tee log-test-SEER_5123.txt
python summarize_results.py SEER_6123 |& tee log-test-SEER_6123.txt
python summarize_results.py SEER_7123 |& tee log-test-SEER_7123.txt
python summarize_results.py SEER_8123 |& tee log-test-SEER_8123.txt
python summarize_results.py SEER_9123 |& tee log-test-SEER_9123.txt
